/**
 * SuggestedQuestions.tsx
 * Demo landing page for the Ask screen with categorized sample questions.
 * Questions are grounded in FCC 26-19 corrected facts.
 *
 * Categories:
 *   - Federal (FCC)    — Section 214, FCC 26-19, notice requirements
 *   - State PUC Rules  — CO, OR, AZ, MN, WA, ID specifics
 *   - Operations       — 911, Lifeline, penalties, timelines
 */
import { Scale, MapPin, Shield, FileText, AlertTriangle } from 'lucide-react';

interface SuggestedQuestionsProps {
  onSelect: (question: string) => void;
}

interface QuestionCategory {
  label: string;
  icon: React.ReactNode;
  color: string;
  bg: string;
  questions: string[];
}

const CATEGORIES: QuestionCategory[] = [
  {
    label: 'FCC Section 214',
    icon: <Scale size={16} strokeWidth={1.5} />,
    color: '#FF3621',
    bg: 'rgba(255,54,33,0.08)',
    questions: [
      'What is Section 214 and do we still need authorization?',
      'What changed with FCC 26-19?',
      'What notice do we give residential customers?',
    ],
  },
  {
    label: 'State PUC Rules',
    icon: <MapPin size={16} strokeWidth={1.5} />,
    color: '#1B3139',
    bg: 'rgba(27,49,57,0.06)',
    questions: [
      "What are Colorado's copper retirement requirements?",
      "What's the timeline for copper retirement in Oregon?",
      "What's different about Arizona?",
    ],
  },
  {
    label: 'Operations & Compliance',
    icon: <Shield size={16} strokeWidth={1.5} />,
    color: '#00A972',
    bg: 'rgba(0,169,114,0.08)',
    questions: [
      '911 coordination requirements?',
      'How do we handle Lifeline subscribers?',
      'What are the penalties for non-compliance?',
    ],
  },
];

export function SuggestedQuestions({ onSelect }: SuggestedQuestionsProps) {
  return (
    <div className="max-w-3xl mx-auto">
      {/* Hero */}
      <div className="flex items-center justify-center gap-2 mb-2">
        <FileText size={20} strokeWidth={1.5} style={{ color: '#FF3621' }} />
        <h2 className="text-lg font-semibold" style={{ color: '#1B3139' }}>
          Regulatory Compliance Assistant
        </h2>
      </div>
      <p className="text-sm text-center mb-6" style={{ color: '#6E8898' }}>
        AI-powered Q&A over 528 regulatory documents — FCC orders, state PUC rules, and compliance guidance.
        Answers are generated by LLM with source citations from Vector Search.
      </p>

      {/* Category cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {CATEGORIES.map((cat) => (
          <div
            key={cat.label}
            className="rounded-lg border p-4"
            style={{ backgroundColor: cat.bg, borderColor: 'rgba(27,49,57,0.1)' }}
          >
            <div className="flex items-center gap-2 mb-3">
              <span style={{ color: cat.color }}>{cat.icon}</span>
              <span className="text-xs font-semibold tracking-wide uppercase" style={{ color: cat.color }}>
                {cat.label}
              </span>
            </div>
            <div className="space-y-2">
              {cat.questions.map((q) => (
                <button
                  key={q}
                  onClick={() => onSelect(q)}
                  className="w-full text-left px-3 py-2 text-xs rounded-md border transition-colors"
                  style={{
                    backgroundColor: '#FFFFFF',
                    borderColor: 'rgba(27,49,57,0.12)',
                    color: '#1B3139',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.backgroundColor = '#FF3621';
                    e.currentTarget.style.color = '#FFFFFF';
                    e.currentTarget.style.borderColor = '#FF3621';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = '#FFFFFF';
                    e.currentTarget.style.color = '#1B3139';
                    e.currentTarget.style.borderColor = 'rgba(27,49,57,0.12)';
                  }}
                >
                  {q}
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Hint */}
      <div className="flex items-center justify-center gap-1.5 text-xs" style={{ color: '#6E8898' }}>
        <AlertTriangle size={12} strokeWidth={1.5} />
        <span>All data is synthetic. For demo purposes only — not legal advice.</span>
      </div>
    </div>
  );
}
